### ISSUE TITLE
Conda installation instructions PackagesNotFoundError

### ISSUE THREAD

**Issue by thompsonphys** [jroulet/cogwheel#2]
After attempting to run the default installation instructions found in the README, I bumped into the following conda error:
```sh
PackagesNotFoundError: The following packages are not available from current channels:

  - python-lal
  - pymultinest
  - gwpy
  - dynesty
  - python-lalsimulation
```
These are `conda-forge` packages, which is a channel I don't have specified in my global conda config. I did resolve the issue by adding the `conda-forge` channel flag to the installation line:
```sh
conda create --name <environment_name> --file requirements.txt --channel=conda-forge
```
Just wanted to make a note in case anyone else has this problem!

**Comment by ntveem** [comment]
Thanks for flagging this issue!

BTW, if you have issues with the n_live_points argument for Pymultinest,
please omit it and it will use the default value (2048). We'll fix this
issue in the next update.

Best,

Teja

**Comment by jroulet** [comment]
Thanks for the suggestion! I added `--channel conda-forge` to the instructions.
